### ISSUE TITLE
Single Header

### ISSUE THREAD

**Issue by da0x** [eliaskosunen/scnlib#107]
Would be nice to get this library as a single header with no lib dependency.

**Comment by eliaskosunen** [comment]
In the next major version (v3), there will be no compiled dependencies, as the reliance on simdutf is removed. FastFloat (which is header-only) is still needed, and will be for the foreseeable future, as I don't intend to intend to implement that myself, and there's no way I could do it any better.

As for the single-header question, v3 will also consist of less files, but there will still be a clear split between the public interface and the private implementation. I don't intend to add support for a header-only mode in the short-term future, and it's not really a practice I would want to encourage.  The public interface will only be a single header file, though.
