### ISSUE TITLE
how to parse string 

### ISSUE THREAD

**Issue by mirekh68** [eliaskosunen/scnlib#108]
I have problem with parsing example like this:

auto result1 = scn::scan<std::string, double>(":x22x , 3.14", ":x{}x , {}");

Either I dont understand something or documentation is missing important case ?
the other case like this:

auto result1 = scn::scan<std::string, double>(":x22x , 3.14", ":x{}x , {}");
works as expected. How to tackle the string case ?

**Comment by eliaskosunen** [comment]
The default behavior for reading a string is to scan until a whitespace character: https://www.scnlib.dev/latest/group__format-string.html#type-string, which is the same behavior as with `scanf` and `%s`. Therefore, the following is what happens:

```cpp
auto result = scn::scan<std::string>("x22x", "x{}");
// result->value() == "22x"
```

The format string following the `{}` is not inspected to determine, what characters to accept when reading a string, and when to stop reading. To determine what characters to accept, the character set syntax can be used:

```cpp
// [^x]: accept everything but 'x'
auto result = scn::scan<std::string, double>(":x22x , 3.14", ":x{:[^x]}x , {}");
// std::get<0>(result->values()) == "22"
// std::get<1>(result->values()) == 3.14
```

Your second case is identical to the first, so I can't help with that.
