### ISSUE TITLE
Scan fails when using double newlines

### ISSUE THREAD

**Issue by Jonathan-Greve** [eliaskosunen/scnlib#116]
Hi loving the library!

I have a minor issue with scanning some strings.

This doesn't scan succesfully:
 ```auto scan_result = scn::scan<int>("0\n\n", "{}\n\n");```

similarly these won't either:
```auto scan_result = scn::scan<int>("0\n\r", "{}\n\r");```
```auto scan_result = scn::scan<int>("0\r\n", "{}\r\n");```
```auto scan_result = scn::scan<int>("0\r\r", "{}\r\r");```

These will scan succesfully:
```auto scan_result = scn::scan<int>("0\r\r", "{}");```
```auto scan_result = scn::scan<int>("0\r\r", "{}\0\n");``` (I also don't understand why this is successful since `"\r\r" != "\0\n"`

Reproduced here:
https://godbolt.org/z/YY6K7Tzch

The results error message is: `"Unexpected end of source"`

Could you please offer some insight on what is happening here?

**Comment by eliaskosunen** [comment]
This is a bug, fixed in 58ae085570dd0bcbdc505bd790a813f8ccc8f5f4. Thanks for reporting!
