### ISSUE TITLE
Support using an existing fast_float CMake target

### ISSUE THREAD

**Issue by ajtribick** [eliaskosunen/scnlib#118]
Suppose I have both fast_float and scnlib as subdirectories/submodules of my project. If possible, I would like to be able to have scnlib use the existing `FastFloat::fast_float` target generated by including the fast_float subdirectory rather than trying to find an installed version via `find_package` or using `FetchContent`.

This would be useful in situations where the build infrastructure does not support doing downloads at build time.

**Comment by eliaskosunen** [comment]
In 74c39b765abb19df3b3607a294d1b042e3dab022, `find_package` is only called if the target is not already defined. How's that?

**Comment by ajtribick** [comment]
Great, thanks a lot!
