### ISSUE TITLE
Scaning to Char []?

### ISSUE THREAD

**Issue by nanoric** [eliaskosunen/scnlib#18]
Without support to char[], we must construcat at least one std::string before calling scn::scan, if the input contains string, which is anoying.

What's more, istream support scanning to char[]. People (such as me) will get confused if scanning into char[] is unsupported when  porting code from istream from scnlib.

**Comment by eliaskosunen** [comment]
Arrays are problematic to handle, because they decay to pointers easily. `string_view`s and `span`s can be scanned, however, each giving slightly different behavior:

```cpp
// Read exactly 4 characters (with span)
char arr[4] = {0};
auto s = scn::make_span(arr, 4);
scn::scan("1234", "{}", s);
// s == {'1', '2', '3', '4'}

// Read until whitespace, without allocating (with string_view)
// Requires a contiguous_range as input
string_view s;
scn::scan("1234", "{}", s);
// s == {'1', '2', '3', '4'}
// s points to the input range; watch out about lifetime issues
```

Because the inputs given to `scn::scan` are ranges, you could also just use existing standard algorithms, like `std::copy`.

**Comment by nanoric** [comment]
Good. both make_span and string_view are easy to use.
But, string_view confused me. Because when I use std::string_view, MSVC failed to compile.
The correct one is scn::string_view. 
Anyway, its a good solution.

**Comment by eliaskosunen** [comment]
`std::string_view`s can also now be scanned in 2068067. Thanks for pointing that out, I thought it already worked. Should've had a test for it...
