### ISSUE TITLE
Scanning with width, or customize separator.

### ISSUE THREAD

**Issue by nanoric** [eliaskosunen/scnlib#19]
What if input string is not seperate by space?
```cpp
    std::string_view v1, v2;
    auto ret = scn::scanf("42,43", "%2s,%2s", v1, v2);
// or
    auto ret = scn::scan("42,43", "{:2}{:2}", v1, v2);
```
both failed. 
but sscanf works fine with following code:
```cpp
    char buf1[20], buf2[20];
    sscanf("42,43", "%2s,%2s", buf1, buf2);
```

**Comment by eliaskosunen** [comment]
There's better string parsing support in the roadmap. With the present facilities, a fixed number of chars can be scanned with using a `span`:

```cpp
char buf1[20], buf2[20];
auto span1 = scn::make_span(buf1), span2 = make_span(buf2);
auto ret = scn::scan("42,43", "{},{}", span1, span2);
// buf1 == {'4','2'}
// buf2 == {'4','3'}
```

Although, that's probably not really necessary: something like `std::copy_n` could be used, since the input given to `scan` is just a range:

```cpp
char buf1[20], buf2[20];
auto it = std::copy_n("42,43", 2, buf1);
// buf1 == {'4',2'}
++it; // skip ','
it = std::copy_n(it, 2, buf2);
// it points at the null terminator of the string literal
// buf2 == {'4','3'}
```

As an aside, the format string parsing for `scn::scanf` is really lacking. It's possible I'll be taking it out in the next release, as I don't really want to be maintaining two distinct format string syntaxes.

**Comment by nanoric** [comment]
In fact, I don't care about scanf. 
But I am failed to compile this example:
```cpp
char buf1[20], buf2[20];
auto span1 = scn::make_span(buf1), span2 = make_span(buf2);
auto ret = scn::scan("42,43", "{},{}", span1, span2);
// buf1 == {'4','2'}
// buf2 == {'4','3'}

```
version: SHA-1: 3601563f310cc8955d6cde6e957b3732154f9dfa

**Comment by nanoric** [comment]
In this issue, I want to say that if there is a string as output, all continous inputs will be scaned into that string.
In this example, "42,43" will be scaned into first string, left nothing to the second string.
So this is why specificing a width is necessary.

**Comment by nanoric** [comment]
Even tough std::copy_n can to what I want, but why a scanning library does'nt support that?
For example, you can parse "123456" by just write a function parse_int and invoke. But since we have scnlib, we of cause will want to make the whole thing easier. 
Since sscanf can parse an input like "42,43" into two string, why scnlib couldn't?

**Comment by eliaskosunen** [comment]
My bad, I forgot to include the size of the span in my example. Sorry about that.

The size of the span determines the amount of characters (bytes) to be read from the input range. So, to read two chars, the size of the span needs to be 2.

```cpp
char buf[1024] = {0};
auto s = make_span(buf, 3);
scan("abcdef", "{}", s);
// s == {'a', 'b', 'c'}
```

Your attempt failed, because `scn::scan` tried to read 20 characters (the size of the span was 20) from a five-character string (`"42,43"`).

**Comment by eliaskosunen** [comment]
So, the correct code is:

```cpp
char buf1[20], buf2[20];
auto span1 = scn::make_span(buf1, 2), span2 = make_span(buf2, 2);
auto ret = scn::scan("42,43", "{},{}", span1, span2);
// buf1 == {'4','2'}
// buf2 == {'4','3'}
```

**Comment by nanoric** [comment]
Good, it works.

**Comment by nanoric** [comment]
Anyway, I think haveing a length specifer(or a customize separator) will be better .

I'm working on a project, which has others developers that not that familier with C++. They use some language such python which are pretty easy to use. But for now, for some reason, they have to use C++ to write some code.

the code:
```cpp
std::string_view s1, s2;
scn::scan(input/*"42,43"*/, "{:2},{:2}", s1, s2);
```
or
```cpp
std::string_view s1, s2;
scn::scan(input/*"42,43"*/, "{},{}", s1, s2); // ',' as separator.
```
is simple and clear.

but in this code:
```cpp
char buf1[20], buf2[20];
auto span1 = scn::make_span(buf1, 2), span2 = scn::make_span(buf2, 2);
scn::scan(input/*"42,43"*/, "{:2},{:2}", s1, s2);
```
Developer must pre-allocate memory(declare buffers), and specifc the start and end position of buffers. which is too complex for newbees. Also, if the parsing syntax gets a little more complex, the code gets much more ugly, making it hard for people to review.

If changing the formating syntax is not a good idea, we can make some change outside the format parser, such as :
```cpp
std::string_view s1, s2;
scn::scan(input/*"42,43"*/, "{},{}", lengh_limited(s1, 2), length_limited(s2, 2));
```

What's you opinon about this?
