### ISSUE TITLE
scn::scan/prompt from stdin with literal text does not work

### ISSUE THREAD

**Issue by melak47** [eliaskosunen/scnlib#29]
When trying to scan a format string with a literal at the start, a debug assertions fires:

```
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xstring
Line: 1853

Expression: cannot seek string iterator before begin
```

Code I used, adapted from the examples (using scnlib 0.3):
```cpp
#include <scn/scn.h>
#include <iostream>

int main() {
    int i = 0;
    if (scn::prompt("Hi there! What's your favorite number? ", "uhh, {}", i)) {
        std::cout << "Ooh, " << i << ", interesting!\n";
    }
    else {
        std::cout << "That doesn't look like any number I've ever seen.\n";
    }
}
```

**Comment by melak47** [comment]
It seems to be related specifically to the file putback, it works when you scan from e.g. a string_view.

**Comment by melak47** [comment]
In `range_wrapper::advance`:
https://github.com/eliaskosunen/scnlib/blob/cf9497e809cb1a06b1940571494a58586975639f/include/scn/detail/range.h#L142-L149

the begin iterator of the range is not incremented for the caching cfile iterator.
As far as I can tell, this leads to `operator*` always yielding the same character, thus matching the literal fails.

Also, in `range_wrapper::reset_to_rollback_point`:
https://github.com/eliaskosunen/scnlib/blob/cf9497e809cb1a06b1940571494a58586975639f/include/scn/detail/range.h#L193-L196

the iterator is decremented `m_read` times, 
but doesn't seem to always match how often the iterator was incremented directly, outside of `range_wrapper`.

**Comment by melak47** [comment]
This seems to be resolved on master.

**Comment by eliaskosunen** [comment]
It is, sorry for not responding and fixing this earlier.
