### ISSUE TITLE
Skip an item

### ISSUE THREAD

**Issue by AlfredXiaSF** [eliaskosunen/scnlib#55]
Is there a way to skip an item when use scnlib? I mean in `scanf` we can use `*` to skipt an item:
```cpp
int count;
scanf("%d%*c", &count);
```
`*c` means, that a char will be read but won't be assigned, for example for the input "30a" it will assign 30 to `count`, but 'a' will be ignored.
Is there a similay way in scnlib to implement this?

**Comment by eliaskosunen** [comment]
`scn::discard` provides this functionality:

```cpp
int count;
auto ret = scn::input("{}{}", count, scn::discard<char>());
```

There's no way to achieve this using the format string.
