### ISSUE TITLE
Feature request: Simple way to consider remaining input a failure

### ISSUE THREAD

**Issue by andersjel** [eliaskosunen/scnlib#65]
I often need to scan a string and check that the entire string was consumed. I can do:
```cpp
int num;
auto result = scn::scan(filename, "item-{}.txt", num);
if (result && result.range().empty()) {
    // Filename is valid
}
```
but I would rather type something like:
```cpp
int num;
if (scn::scan_all(filename, "item-{}.txt", num)) {
    // Filename is valid
}
```
Could this be considered (or is there some other simple way to do this that I am missing)?

**Comment by eliaskosunen** [comment]
At least for now, I don't consider this worth increasing the API surface.
