### ISSUE TITLE
Running fuzzers in CI

### ISSUE THREAD

**Issue by AdamKorcz** [eliaskosunen/scnlib#76]
scnlibs fuzzing suite can run in the CI with [ClusterfuzzLite](https://google.github.io/clusterfuzzlite/). 

ClusterfuzzLite can be set up so that only fuzzers affected by a given PR will run.

Is that something that is of interest to the scnlib project? If so, I will be happy to set it up.

**Comment by eliaskosunen** [comment]
I tried setting it up, but couldn't get it to co-operate with CMake. If you're still up for it, I absolutely wouldn't be against it.

**Comment by eliaskosunen** [comment]
Clusterfuzzlite has been integrated for a while now, closing.
