### ISSUE TITLE
Error parsing '+12345' as a float

### ISSUE THREAD

**Issue by TD22057** [eliaskosunen/scnlib#77]
Version 1.1.2

```
#include <iostream>
#include <string_view>
#include <cstdio>
#include <scn/scn.h>

int main()
{
   const char* s = "+12345";
   std::string_view sv( s );
   
   double x;
   auto r = scn::scan( sv, "{}", x );
   if ( r ) std::cout << "scn: got: " << x << "\n";
   else std::cout << "scn: error: '" << r.error().msg() << "'\n";

   if ( sscanf( s, "%lf", &x ) == 1 ) std::cout << "scanf: got: " << x << "\n";
   else std::cout << "scanf: error\n";
         
   return 0;
}

```
yields:
```
scn: error: 'fast_float'
scanf: got: 12345
```
IMO this should work and return 12345.  It's also a bit annoying that the error message just says "fast_float" instead of indicating what the problem is.  Obviously I can guess what the problem is but when this is embedded in a larger application the user will have no idea what fast_float means.

**Comment by ilynxy** [comment]
According to https://github.com/fastfloat/fast_float and https://en.cppreference.com/w/cpp/utility/from_chars a leading '+' sign is forbidden.
IMO, leading '+' sign should be parsed with scnlib.

**Comment by eliaskosunen** [comment]
This works properly in v2, and is now also fixed properly in the latest master. Thanks for reporting!
