### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by SuperWig** [eliaskosunen/scnlib#8]
Trying out the library and can't run the examples. The problem seems to be this line
https://github.com/eliaskosunen/scnlib/blob/b9adabe4806bae4dd749791c09ed5e4acc83af36/include/scn/detail/small_vector.h#L705

**Comment by eliaskosunen** [comment]
Whoops. Should probably have tried to run the examples at some point. Give me a minute.

**Comment by eliaskosunen** [comment]
`acee395` has a temporary fix for this issue. The examples, and reading from `stdin` for that matter, now work without issues.

There seems to be some problems with `erased_stream` which needs to be investigated.

**Comment by eliaskosunen** [comment]
Fixed in 21001af. The issue was in a faulty copy and move constructor of `small_vector`. Thanks for reporting!

**Comment by SuperWig** [comment]
Great! Thanks for the fast fix :)
