### ISSUE TITLE
Add COMPONENT to install targets

### ISSUE THREAD

**Issue by pawelwod** [eliaskosunen/scnlib#81]
Hi,

I created PR #80 that adds COMPONENT keyword to install targets. It makes life easier especially if you want to use the dh-cmake to create DEB package like I did in [this commit](https://github.com/eliaskosunen/scnlib/commit/44506fa67cbd05bbefa3abfc1d2acca3525dea29).

Pls merge it if you think it's something useful.
Thanks :)

**Comment by eliaskosunen** [comment]
PR merged. Thank you!
