### ISSUE TITLE
gcc-10 won't compile with rvalue string_view as range

### ISSUE THREAD

**Issue by phisko** [eliaskosunen/scnlib#83]
The following code doesn't compile in gcc-10:

```cpp
#include <string_view>
#include <scn/scn.h>

int main() {
    int i = 0;
    scn::scan_default(std::string_view("42"), i);
}
```

Errors mention an overload resolution failure due to `priority_tag`. Interestingly, passing a `string_view` as an lvalue (even `const`) works fine.

[errors.txt](https://github.com/eliaskosunen/scnlib/files/10896683/errors.txt)

**Comment by eliaskosunen** [comment]
Gah, the overload resolution rules are a source of pain sometimes. Fixed in latest master, thank you for reporting!
