### ISSUE TITLE
Wich packages does this come with ?

### ISSUE THREAD

**Issue by e2002e** [eliaskosunen/scnlib#90]
Hello, I am using wine on linux, and scnlib is required by a game.
Do you know with which windows application this is packaged ?

**Comment by eliaskosunen** [comment]
Unfortunately I'm not really able to help with that. Proper packaging with all the necessary dependencies included is really up to the library consumers, so in this case, the game itself. It's also possible, that the game does ship with the correct binaries, but can't find them: in that case, you'll need to some additional configuration.

If the game is broken and really doesn't ship with everything it needs, you may need to build the Windows binaries for the library yourself, which on Linux may prove tricky. There are some instructions in the docs.

I'm not aware of any Windows software in general that ships with binaries of this library.
