### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by StellaSmith** [eliaskosunen/scnlib#91]
The readthedocs link in the readme is dead. It results in a 404 page:
![image](https://github.com/eliaskosunen/scnlib/assets/40411082/1a9f2480-2ad3-47c1-a62a-c63bbfb920b5)

**Comment by eliaskosunen** [comment]
Thanks. That's now been fixed: RtD had changed their build process, and it caused it to fail.

It works now, and is also reachable through a new URL, https://scnlib.dev
