### ISSUE TITLE
Can't compile scnlib/2.0.0 on MSVC

### ISSUE THREAD

**Issue by toge** [eliaskosunen/scnlib#97]
Thank you for releasing version 2.0.0!

When I tried to update the conan recipe, I got a compilation errors only with MSVC 19.37.32824.0.
(gcc, clang and apple-clang work fine).

Wolud you help me to solve this problem?

```
src\scn\vscan.cpp(401,67): error C2440: 'initializing': cannot convert from 'initializer list' to 'scn::v2::detail::specs_checker<scn::v2::`anonymous-namespace'::specs_handler<scn::v2::basic_scan_context<wchar_t>>>' [b\build\scn.vcxproj]
src\scn\vscan.cpp(401,67): message : No constructor could take the source type, or constructor overload resolution was ambiguous [b\build\scn.vcxproj]
src\scn\vscan.cpp(384,22): message : while compiling class template member function 'const wchar_t *scn::v2::`anonymous-namespace'::format_handler<false,CharT>::on_format_specs(size_t,const wchar_t *,const wchar_t *)' [b\build\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ]
include\scn/detail/format_string_parser.h(909,19): message : see the first reference to 'scn::v2::`anonymous-namespace'::format_handler<false,CharT>::on_format_specs' in 'scn::v2::detail::parse_replacement_field' [b\build\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ] (compiling source file src\scn\vscan.cpp)
src\scn\vscan.cpp(491,52): message : see reference to class template instantiation 'scn::v2::`anonymous-namespace'::format_handler<false,CharT>' being compiled [b\build\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ]
src\scn\vscan.cpp(570,14): message : see reference to function template instantiation 'scn::v2::scan_expected<ptrdiff_t> scn::v2::`anonymous-namespace'::vscan_internal<wchar_t>(scn::v2::detail::basic_scan_buffer<wchar_t> &,std::basic_string_view<wchar_t,std::char_traits<wchar_t>>,scn::v2::basic_scan_args<scn::v2::wscan_context>,scn::v2::detail::locale_ref)' being compiled [b\build\scn.vcxproj]
```

**Comment by evreqe** [comment]
I was having trouble with MSVC too but I was able to fix it by linking with simdutf.lib AND scn.lib
I thought it would only need scn.lib but it needed both

**Comment by eliaskosunen** [comment]
The reply is correct. The library currently depends on simdutf. This is handled transparently when using CMake. If not, the necessary additional linking is also documented here: https://www.scnlib.dev/latest/index.html#main-without-cmake.

**Comment by RazielXYZ** [comment]
@eliaskosunen the reply is correct, but not relevant for this issue. This issue appears during building scnlib, and simdutf is present. Also, in this specific case, building with C++20 with no other changes works, while C++17 fails. There is also a warning STL4038: The contents of <stdfloat> are available only with C++23 or later. right before the error.
Further testing shows that this only happens when SCN_USE_EXTERNAL_FAST_FLOAT is set to True.

**Comment by eliaskosunen** [comment]
I'm unable to reproduce this locally (2022 17.9 = 19.39) and on CI (2022 17.8 = 19.38, and 2019 16.11 = 19.29). Thus, keeping this as WONTFIX, as I have no way of verifying a patch. Given how this works on VS 2019, it sounds like a version-specific compiler bug. Patches are nevertheless welcome.
